/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class addPatient extends javax.swing.JFrame {

    /**
     * Creates new form addPatient
     */
    public addPatient() {
        initComponents();
        this.setSize(1560, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        patientId = new javax.swing.JTextField();
        firstName1 = new javax.swing.JTextField();
        lastName1 = new javax.swing.JTextField();
        wordNo = new javax.swing.JTextField();
        maritialStatus = new javax.swing.JComboBox<>();
        patientType = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();
        age = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        bedNo = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        add = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        viewPatient = new javax.swing.JButton();
        updatePatient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(patientId);
        patientId.setBounds(370, 260, 330, 40);

        firstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName1ActionPerformed(evt);
            }
        });
        jPanel1.add(firstName1);
        firstName1.setBounds(380, 350, 320, 40);
        jPanel1.add(lastName1);
        lastName1.setBounds(910, 360, 320, 40);
        jPanel1.add(wordNo);
        wordNo.setBounds(350, 890, 320, 40);

        maritialStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[...Select One...]", "Single", "Married", " " }));
        maritialStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maritialStatusActionPerformed(evt);
            }
        });
        jPanel1.add(maritialStatus);
        maritialStatus.setBounds(370, 550, 170, 40);

        patientType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[...Select One...]", "Indoor", "Outdoor", " ", " " }));
        patientType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTypeActionPerformed(evt);
            }
        });
        jPanel1.add(patientType);
        patientType.setBounds(380, 760, 170, 40);

        date.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(date);
        date.setBounds(910, 550, 180, 40);
        jPanel1.add(age);
        age.setBounds(370, 440, 320, 40);

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        jPanel1.add(city);
        city.setBounds(370, 700, 320, 40);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[...Select One...]", "Male", "Female", "Other", " " }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender);
        gender.setBounds(910, 450, 170, 40);
        jPanel1.add(bedNo);
        bedNo.setBounds(900, 890, 320, 40);
        jPanel1.add(phn);
        phn.setBounds(900, 700, 320, 40);
        jPanel1.add(address);
        address.setBounds(370, 620, 440, 40);

        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/add.png"))); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(1190, 210, 200, 100);

        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/home.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(1240, 60, 130, 120);

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/logouticon.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(1370, 60, 150, 120);

        viewPatient.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        viewPatient.setText("View Patient");
        viewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientActionPerformed(evt);
            }
        });
        jPanel1.add(viewPatient);
        viewPatient.setBounds(420, 10, 150, 40);

        updatePatient.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        updatePatient.setText("Update Patient");
        updatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientActionPerformed(evt);
            }
        });
        jPanel1.add(updatePatient);
        updatePatient.setBounds(210, 10, 160, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coverimage/addpatient.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1544, 970);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maritialStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maritialStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maritialStatusActionPerformed

    private void patientTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTypeActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
       ImageIcon i=new ImageIcon(getClass().getResource("add1.png"));
        add.setIcon(i);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
ImageIcon i=new ImageIcon(getClass().getResource("add.png"));
        add.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
ImageIcon i=new ImageIcon(getClass().getResource("logouticon1.png"));
        logout.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
ImageIcon i=new ImageIcon(getClass().getResource("logouticon.png"));
        logout.setIcon(i);          // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
ImageIcon i=new ImageIcon(getClass().getResource("home_1.png"));
        home.setIcon(i);          // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
ImageIcon i=new ImageIcon(getClass().getResource("home.png"));
        home.setIcon(i);          // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseExited

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void firstName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName1ActionPerformed

    private void updatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePatientActionPerformed
        new updatePatient().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updatePatientActionPerformed

    private void viewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientActionPerformed
       new viewpatient().setVisible(true);    
       this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_viewPatientActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
      new adminPortal().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
       new HomePage().setVisible(true);   
       this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        try{
           Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sd","root","12345678");
            Statement st =cn.createStatement();
            String sql= "insert into patient "
                   +"values ('"+patientId.getText()+"','"+firstName1.getText()+"', '"+lastName1.getText()+"', '"+age.getText()+"', '"+gender.getSelectedItem()+"', '"+maritialStatus.getSelectedItem()+"', '"+address.getText()+"','"+city.getText()+"','"+phn.getText()+"','"+patientType.getSelectedItem()+"','"+date.getDate()+"')";
            st.executeUpdate(sql);
            this.setVisible(false);
            new addPatient().setVisible(true);
            JOptionPane.showMessageDialog(null, "Added Successfully in the Database");
        
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_addMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField bedNo;
    private javax.swing.JTextField city;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField firstName1;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName1;
    private javax.swing.JLabel logout;
    private javax.swing.JComboBox<String> maritialStatus;
    private javax.swing.JTextField patientId;
    private javax.swing.JComboBox<String> patientType;
    private javax.swing.JTextField phn;
    private javax.swing.JButton updatePatient;
    private javax.swing.JButton viewPatient;
    private javax.swing.JTextField wordNo;
    // End of variables declaration//GEN-END:variables
}
