/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class adminPortal extends javax.swing.JFrame {

    /**
     * Creates new form adminPortal
     */
    public adminPortal() {
        initComponents();
        this.setSize(1540, 970);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        docotr = new javax.swing.JLabel();
        appointment = new javax.swing.JLabel();
        patient = new javax.swing.JLabel();
        receptionist = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        docotr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        docotr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/Doctor Details.png"))); // NOI18N
        docotr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docotrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                docotrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                docotrMouseExited(evt);
            }
        });
        jPanel1.add(docotr);
        docotr.setBounds(1060, 210, 400, 300);

        appointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/Appointments.png"))); // NOI18N
        appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentMouseClicked(evt);
            }
        });
        jPanel1.add(appointment);
        appointment.setBounds(1060, 550, 400, 300);

        patient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/patient.png"))); // NOI18N
        patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientMouseClicked(evt);
            }
        });
        jPanel1.add(patient);
        patient.setBounds(590, 200, 400, 300);

        receptionist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(receptionist);
        receptionist.setBounds(590, 540, 400, 300);

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(1070, 60, 310, 110);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coverimage/adminPortal.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1540, 970);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void docotrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docotrMouseEntered
 
    }//GEN-LAST:event_docotrMouseEntered

    private void docotrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docotrMouseExited
 ImageIcon i=new ImageIcon(getClass().getResource("Doctor Details.png"));
        docotr.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_docotrMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
 ImageIcon i=new ImageIcon(getClass().getResource("glogout.png"));
        logout.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
ImageIcon i;
        i = new ImageIcon(getClass().getResource("logout.png"));
        logout.setIcon(i);         // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
      int choice=JOptionPane.showConfirmDialog(null, "Do ypu want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
      if(choice==JOptionPane.YES_OPTION)
      {
          new HomePage().setVisible(true);
      }
      else
      {
          this.setVisible(true);
      }
    }//GEN-LAST:event_logoutMouseClicked

    private void patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseClicked
new addPatient().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_patientMouseClicked

    private void appointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentMouseClicked
new addAppointment().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentMouseClicked

    private void docotrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docotrMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_docotrMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointment;
    private javax.swing.JLabel docotr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel patient;
    private javax.swing.JLabel receptionist;
    // End of variables declaration//GEN-END:variables
}
